# -*- coding: utf-8 -*-
"""calculator with loop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-iNjGGGFZ0mtfEU15jbpCatafWTv0Yz0
"""

def add(num1, num2):
	return num1 + num2

# Function to subtract two numbers
def subtract(num1, num2):
	return num1 - num2

# Function to multiply two numbers
def multiply(num1, num2):
	return num1 * num2

# Function to divide two numbers
def divide(num1, num2):
	return num1 / num2

print("Please select operation -\n" \
		"1. Add\n" \
		"2. Subtract\n" \
		"3. Multiply\n" \
		"4. Divide\n")

cont = 1
while(cont == 1):
  # Take input from the user
  select = int(input("Select operations form 1, 2, 3, 4 :"))

  number_1 = int(input("Enter first number: "))
  number_2 = int(input("Enter second number: "))

  if select == 1:
    print(number_1, "+", number_2, "=",
            add(number_1, number_2))

  elif select == 2:
    print(number_1, "-", number_2, "=",
            subtract(number_1, number_2))

  elif select == 3:
    print(number_1, "*", number_2, "=",
            multiply(number_1, number_2))

  elif select == 4:
    print(number_1, "/", number_2, "=",
            divide(number_1, number_2))
  else:
    print("Invalid input")

  cont= int(input("Do you want to continue? If yes press 1 if not press any key:-  "))